version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-ctr
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    volumes:
      - ".:/opt/spark/"
  spark-worker:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-worker1-ctr
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ".:/opt/spark/"
    ports:
      - "8081:8081"
      - "4041:4040"
  spark-worker2:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-worker2-ctr
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ".:/opt/spark/"
    ports:
      - "8082:8081"
      - "4042:4040"
  spark-worker3:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-worker3-ctr
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ".:/opt/spark/"
    ports:
      - "8083:8081"
      - "4043:4040"
  postgres:
    image: postgres:13
    container_name: postgres-orion
    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion
      POSTGRES_DB: orion
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orion"]
      interval: 5s
      retries: 5
    restart: always
  mongo-db:
    image: mongo
    container_name: mongo-ctr
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper-ctr
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka-ctr
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no

    depends_on:
      - zookeeper
volumes:
  dbdata:
